name: flutter_modular_app
packages:
  - core/**
  - features/**



command:
    bootstrap:
      environment:
        sdk: ^3.10.1
        flutter: ">=1.17.0"

      dependencies:
        dio: ^5.9.0

      dev_dependencies:
        flutter_lints: ^6.0.0